version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/certificates:/etc/traefik/certificates
    labels:
      - traefik.http.routers.reverse-proxy.entrypoints=https
      - traefik.http.routers.reverse-proxy.tls=true

  static-web-server:
    build: static_web_server
    labels:
      - traefik.http.routers.static-web-server.rule=Host(`localhost`)
      - traefik.http.services.static-web-server.loadbalancer.server.port=80
      - traefik.http.routers.static-web-server.entrypoints=https
      - traefik.http.routers.static-web-server.tls=true
    deploy:
      replicas: 2

  api:
    build: api
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.api.loadbalancer.server.port=7000
      - traefik.http.services.api.loadbalancer.sticky=true
      - traefik.http.services.api.loadbalancer.sticky.cookie.name=apicookie
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
    deploy:
      replicas: 1

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: