providers:
  docker: { }
api:
  dashboard: true
  insecure: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
tls:
  certificates:
    - certFile: /etc/traefik/certificates/cert.pem
      keyFile: /etc/traefik/certificates/key.pem