FROM eclipse-temurin:21

WORKDIR /app

COPY /target/httpinfrastructure-api-1.0-jar-with-dependencies.jar /app

ENTRYPOINT ["java", "-jar", "httpinfrastructure-api-1.0-jar-with-dependencies.jar"]

EXPOSE 7000